name: 'github-actions-rsync'
description: 'Github action for rsync'
inputs:
  rsync_options:
    description: 'Flags for rsync'
    required: false
    default: ''
  rsync_target:
    description: 'Destination filepath'
    required: true
  rsync_source:
    description: 'Source filepath'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
